local main_unit_size_caste_info = {
	["dan_anglian_champions"] = { ["unit_key"] = "dan_anglian_champions", ["caste"] = "medium", ["num_men"] = 160 },
	["dan_anglian_marauders"] = { ["unit_key"] = "dan_anglian_marauders", ["caste"] = "super_heavy", ["num_men"] = 80 },
	["dan_anglian_raiders"] = { ["unit_key"] = "dan_anglian_raiders", ["caste"] = "medium", ["num_men"] = 120 },
	["dan_archers"] = { ["unit_key"] = "dan_archers", ["caste"] = "light", ["num_men"] = 60 },
	["dan_armoured_archers"] = { ["unit_key"] = "dan_armoured_archers", ["caste"] = "medium", ["num_men"] = 80 },
	["dan_axemen"] = { ["unit_key"] = "dan_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_berserkers"] = { ["unit_key"] = "dan_berserkers", ["caste"] = "very_heavy", ["num_men"] = 24 },
	["dan_catapult"] = { ["unit_key"] = "dan_catapult", ["caste"] = "light", ["num_men"] = 40 },
	["dan_ceorl_archers"] = { ["unit_key"] = "dan_ceorl_archers", ["caste"] = "light", ["num_men"] = 60 },
	["dan_ceorl_axemen"] = { ["unit_key"] = "dan_ceorl_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_ceorl_javelinmen"] = { ["unit_key"] = "dan_ceorl_javelinmen", ["caste"] = "very_light", ["num_men"] = 60 },
	["dan_ceorl_spearmen"] = { ["unit_key"] = "dan_ceorl_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_danelaw_huscarls"] = { ["unit_key"] = "dan_danelaw_huscarls", ["caste"] = "heavy", ["num_men"] = 160 },
	["dan_fyrd_archers"] = { ["unit_key"] = "dan_fyrd_archers", ["caste"] = "very_light", ["num_men"] = 60 },
	["dan_fyrd_spearmen"] = { ["unit_key"] = "dan_fyrd_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_great_axemen"] = { ["unit_key"] = "dan_great_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_huscarls"] = { ["unit_key"] = "dan_huscarls", ["caste"] = "heavy", ["num_men"] = 120 },
	["dan_jarls_horsemen"] = { ["unit_key"] = "dan_jarls_horsemen", ["caste"] = "heavy", ["num_men"] = 48 },
	["dan_jarls_huscarls"] = { ["unit_key"] = "dan_jarls_huscarls", ["caste"] = "super_heavy", ["num_men"] = 48 },
	["dan_javelinmen"] = { ["unit_key"] = "dan_javelinmen", ["caste"] = "light", ["num_men"] = 60 },
	["dan_long_axemen"] = { ["unit_key"] = "dan_long_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_mailed_archers"] = { ["unit_key"] = "dan_mailed_archers", ["caste"] = "medium", ["num_men"] = 80 },
	["dan_mailed_horsemen"] = { ["unit_key"] = "dan_mailed_horsemen", ["caste"] = "super_heavy", ["num_men"] = 48 },
	["dan_mailed_swordsmen"] = { ["unit_key"] = "dan_mailed_swordsmen", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["dan_northumbrian_mailed_thegns"] = { ["unit_key"] = "dan_northumbrian_mailed_thegns", ["caste"] = "super_heavy", ["num_men"] = 80 },
	["dan_northumbrian_thegns"] = { ["unit_key"] = "dan_northumbrian_thegns", ["caste"] = "heavy", ["num_men"] = 120 },
	["dan_royal_huscarls"] = { ["unit_key"] = "dan_royal_huscarls", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["dan_scout_horsemen"] = { ["unit_key"] = "dan_scout_horsemen", ["caste"] = "light", ["num_men"] = 24 },
	["dan_shield_biters"] = { ["unit_key"] = "dan_shield_biters", ["caste"] = "heavy", ["num_men"] = 40 },
	["dan_spearmen"] = { ["unit_key"] = "dan_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["dan_sword_hersir"] = { ["unit_key"] = "dan_sword_hersir", ["caste"] = "heavy", ["num_men"] = 80 },
	["dan_sword_hirdmen"] = { ["unit_key"] = "dan_sword_hirdmen", ["caste"] = "heavy", ["num_men"] = 120 },
	["dan_thegn_horsemen"] = { ["unit_key"] = "dan_thegn_horsemen", ["caste"] = "medium", ["num_men"] = 60 },
	["dan_warlords_companions"] = { ["unit_key"] = "dan_warlords_companions", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["eng_catapult"] = { ["unit_key"] = "eng_catapult", ["caste"] = "light", ["num_men"] = 40 },
	["eng_ceorl_archers"] = { ["unit_key"] = "eng_ceorl_archers", ["caste"] = "light", ["num_men"] = 60 },
	["eng_ceorl_axemen"] = { ["unit_key"] = "eng_ceorl_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_ceorl_javelinmen"] = { ["unit_key"] = "eng_ceorl_javelinmen", ["caste"] = "light", ["num_men"] = 60 },
	["eng_ceorl_spearmen"] = { ["unit_key"] = "eng_ceorl_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_earls_horsemen"] = { ["unit_key"] = "eng_earls_horsemen", ["caste"] = "heavy", ["num_men"] = 48 },
	["eng_earls_spearmen"] = { ["unit_key"] = "eng_earls_spearmen", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["eng_earls_thegns"] = { ["unit_key"] = "eng_earls_thegns", ["caste"] = "medium", ["num_men"] = 80 },
	["eng_fyrd_archers"] = { ["unit_key"] = "eng_fyrd_archers", ["caste"] = "light", ["num_men"] = 60 },
	["eng_fyrd_axemen"] = { ["unit_key"] = "eng_fyrd_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_fyrd_javelinmen"] = { ["unit_key"] = "eng_fyrd_javelinmen", ["caste"] = "light", ["num_men"] = 60 },
	["eng_fyrd_spearmen"] = { ["unit_key"] = "eng_fyrd_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_long_axemen"] = { ["unit_key"] = "eng_long_axemen", ["caste"] = "medium", ["num_men"] = 80 },
	["eng_mailed_horsemen"] = { ["unit_key"] = "eng_mailed_horsemen", ["caste"] = "medium", ["num_men"] = 48 },
	["eng_mailed_long_axemen"] = { ["unit_key"] = "eng_mailed_long_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_mailed_seaxs"] = { ["unit_key"] = "eng_mailed_seaxs", ["caste"] = "medium", ["num_men"] = 160 },
	["eng_mailed_spearmen"] = { ["unit_key"] = "eng_mailed_spearmen", ["caste"] = "medium", ["num_men"] = 160 },
	["eng_mailed_thegns"] = { ["unit_key"] = "eng_mailed_thegns", ["caste"] = "super_heavy", ["num_men"] = 40 },
	["eng_marcher_armoured_spearmen"] = { ["unit_key"] = "eng_marcher_armoured_spearmen", ["caste"] = "heavy", ["num_men"] = 80 },
	["eng_marcher_mailed_spearmen"] = { ["unit_key"] = "eng_marcher_mailed_spearmen", ["caste"] = "medium", ["num_men"] = 160 },
	["eng_marcher_spearmen"] = { ["unit_key"] = "eng_marcher_spearmen", ["caste"] = "medium", ["num_men"] = 120 },
	["eng_militia_fyrd_archers"] = { ["unit_key"] = "eng_militia_fyrd_archers", ["caste"] = "medium", ["num_men"] = 60 },
	["eng_militia_fyrd_spearmen"] = { ["unit_key"] = "eng_militia_fyrd_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_royal_bodyguard"] = { ["unit_key"] = "eng_royal_bodyguard", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["eng_royal_companions"] = { ["unit_key"] = "eng_royal_companions", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["eng_royal_huscarls"] = { ["unit_key"] = "eng_royal_huscarls", ["caste"] = "heavy", ["num_men"] = 160 },
	["eng_royal_thegns"] = { ["unit_key"] = "eng_royal_thegns", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["eng_scout_horsemen"] = { ["unit_key"] = "eng_scout_horsemen", ["caste"] = "light", ["num_men"] = 24 },
	["eng_seax_warriors"] = { ["unit_key"] = "eng_seax_warriors", ["caste"] = "medium", ["num_men"] = 120 },
	["eng_select_fyrd_archers"] = { ["unit_key"] = "eng_select_fyrd_archers", ["caste"] = "medium", ["num_men"] = 60 },
	["eng_select_fyrd_spearmen"] = { ["unit_key"] = "eng_select_fyrd_spearmen", ["caste"] = "medium", ["num_men"] = 120 },
	["eng_select_militia_spearmen"] = { ["unit_key"] = "eng_select_militia_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["eng_thegn_horsemen"] = { ["unit_key"] = "eng_thegn_horsemen", ["caste"] = "medium", ["num_men"] = 48 },
	["eng_thegn_spearmen"] = { ["unit_key"] = "eng_thegn_spearmen", ["caste"] = "heavy", ["num_men"] = 80 },
	["eng_thegns"] = { ["unit_key"] = "eng_thegns", ["caste"] = "heavy", ["num_men"] = 80 },
	["est_archers"] = { ["unit_key"] = "est_archers", ["caste"] = "light", ["num_men"] = 60 },
	["est_axe_warriors"] = { ["unit_key"] = "est_axe_warriors", ["caste"] = "medium", ["num_men"] = 120 },
	["est_axemen"] = { ["unit_key"] = "est_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["est_berserkers"] = { ["unit_key"] = "est_berserkers", ["caste"] = "heavy", ["num_men"] = 40 },
	["est_catapult"] = { ["unit_key"] = "est_catapult", ["caste"] = "light", ["num_men"] = 40 },
	["est_champions"] = { ["unit_key"] = "est_champions", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["est_fighters"] = { ["unit_key"] = "est_fighters", ["caste"] = "very_light", ["num_men"] = 120 },
	["est_great_axes"] = { ["unit_key"] = "est_great_axes", ["caste"] = "light", ["num_men"] = 160 },
	["est_hearthguard"] = { ["unit_key"] = "est_hearthguard", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["est_hirdmen"] = { ["unit_key"] = "est_hirdmen", ["caste"] = "heavy", ["num_men"] = 120 },
	["est_horsemen"] = { ["unit_key"] = "est_horsemen", ["caste"] = "medium", ["num_men"] = 60 },
	["est_hunters"] = { ["unit_key"] = "est_hunters", ["caste"] = "light", ["num_men"] = 24 },
	["est_huskarls"] = { ["unit_key"] = "est_huskarls", ["caste"] = "heavy", ["num_men"] = 160 },
	["est_javelinmen"] = { ["unit_key"] = "est_javelinmen", ["caste"] = "light", ["num_men"] = 80 },
	["est_kerns"] = { ["unit_key"] = "est_kerns", ["caste"] = "light", ["num_men"] = 60 },
	["est_levy_javelinmen"] = { ["unit_key"] = "est_levy_javelinmen", ["caste"] = "light", ["num_men"] = 60 },
	["est_long_axes"] = { ["unit_key"] = "est_long_axes", ["caste"] = "medium", ["num_men"] = 120 },
	["est_mailed_axemen"] = { ["unit_key"] = "est_mailed_axemen", ["caste"] = "heavy", ["num_men"] = 120 },
	["est_mailed_horsemen"] = { ["unit_key"] = "est_mailed_horsemen", ["caste"] = "very_light", ["num_men"] = 48 },
	["est_marauders"] = { ["unit_key"] = "est_marauders", ["caste"] = "light", ["num_men"] = 160 },
	["est_norse_hersir"] = { ["unit_key"] = "est_norse_hersir", ["caste"] = "medium", ["num_men"] = 80 },
	["est_norse_mailed_hersir"] = { ["unit_key"] = "est_norse_mailed_hersir", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["est_norse_warriors"] = { ["unit_key"] = "est_norse_warriors", ["caste"] = "light", ["num_men"] = 120 },
	["est_raiders"] = { ["unit_key"] = "est_raiders", ["caste"] = "light", ["num_men"] = 48 },
	["est_royal_huskarls"] = { ["unit_key"] = "est_royal_huskarls", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["est_scouts"] = { ["unit_key"] = "est_scouts", ["caste"] = "light", ["num_men"] = 24 },
	["est_shield_biters"] = { ["unit_key"] = "est_shield_biters", ["caste"] = "very_heavy", ["num_men"] = 40 },
	["est_spear_guard"] = { ["unit_key"] = "est_spear_guard", ["caste"] = "heavy", ["num_men"] = 120 },
	["est_spear_hirdmen"] = { ["unit_key"] = "est_spear_hirdmen", ["caste"] = "medium", ["num_men"] = 120 },
	["est_spearband"] = { ["unit_key"] = "est_spearband", ["caste"] = "light", ["num_men"] = 160 },
	["est_spearmen"] = { ["unit_key"] = "est_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["est_warband"] = { ["unit_key"] = "est_warband", ["caste"] = "light", ["num_men"] = 200 },
	["est_wood_kerns"] = { ["unit_key"] = "est_wood_kerns", ["caste"] = "light", ["num_men"] = 80 },
	["iri_airig_horsemen"] = { ["unit_key"] = "iri_airig_horsemen", ["caste"] = "heavy", ["num_men"] = 60 },
	["iri_airig_mailed_horsemen"] = { ["unit_key"] = "iri_airig_mailed_horsemen", ["caste"] = "heavy", ["num_men"] = 48 },
	["iri_airig_swordsmen"] = { ["unit_key"] = "iri_airig_swordsmen", ["caste"] = "heavy", ["num_men"] = 40 },
	["iri_airig_warband"] = { ["unit_key"] = "iri_airig_warband", ["caste"] = "heavy", ["num_men"] = 80 },
	["iri_catapult"] = { ["unit_key"] = "iri_catapult", ["caste"] = "light", ["num_men"] = 24 },
	["iri_fianna_band"] = { ["unit_key"] = "iri_fianna_band", ["caste"] = "medium", ["num_men"] = 120 },
	["iri_fianna_swordsmen"] = { ["unit_key"] = "iri_fianna_swordsmen", ["caste"] = "medium", ["num_men"] = 160 },
	["iri_foreign_warriors"] = { ["unit_key"] = "iri_foreign_warriors", ["caste"] = "medium", ["num_men"] = 80 },
	["iri_freemen_archers"] = { ["unit_key"] = "iri_freemen_archers", ["caste"] = "light", ["num_men"] = 80 },
	["iri_freemen_axemen"] = { ["unit_key"] = "iri_freemen_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["iri_freemen_javelinmen"] = { ["unit_key"] = "iri_freemen_javelinmen", ["caste"] = "light", ["num_men"] = 80 },
	["iri_freemen_spearmen"] = { ["unit_key"] = "iri_freemen_spearmen", ["caste"] = "light", ["num_men"] = 200 },
	["iri_gallowglasses"] = { ["unit_key"] = "iri_gallowglasses", ["caste"] = "medium", ["num_men"] = 160 },
	["iri_horse_boys"] = { ["unit_key"] = "iri_horse_boys", ["caste"] = "light", ["num_men"] = 64 },
	["iri_household_horsemen"] = { ["unit_key"] = "iri_household_horsemen", ["caste"] = "heavy", ["num_men"] = 40 },
	["iri_household_riders"] = { ["unit_key"] = "iri_household_riders", ["caste"] = "heavy", ["num_men"] = 32 },
	["iri_kern_axemen"] = { ["unit_key"] = "iri_kern_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["iri_kern_raiders"] = { ["unit_key"] = "iri_kern_raiders", ["caste"] = "light", ["num_men"] = 24 },
	["iri_kern_spearmen"] = { ["unit_key"] = "iri_kern_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["iri_kern_swordsmen"] = { ["unit_key"] = "iri_kern_swordsmen", ["caste"] = "light", ["num_men"] = 160 },
	["iri_kerns"] = { ["unit_key"] = "iri_kerns", ["caste"] = "light", ["num_men"] = 80 },
	["iri_mailed_fianna"] = { ["unit_key"] = "iri_mailed_fianna", ["caste"] = "heavy", ["num_men"] = 40 },
	["iri_mounted_kerns"] = { ["unit_key"] = "iri_mounted_kerns", ["caste"] = "light", ["num_men"] = 60 },
	["iri_raider_swordsmen"] = { ["unit_key"] = "iri_raider_swordsmen", ["caste"] = "light", ["num_men"] = 160 },
	["iri_serf_archers"] = { ["unit_key"] = "iri_serf_archers", ["caste"] = "light", ["num_men"] = 60 },
	["iri_spear_raiders"] = { ["unit_key"] = "iri_spear_raiders", ["caste"] = "heavy", ["num_men"] = 120 },
	["iri_wolf_hounds"] = { ["unit_key"] = "iri_wolf_hounds", ["caste"] = "light", ["num_men"] = 24 },
	["iri_wood_kerns"] = { ["unit_key"] = "iri_wood_kerns", ["caste"] = "light", ["num_men"] = 48 },
	["iri_wood_spears"] = { ["unit_key"] = "iri_wood_spears", ["caste"] = "medium", ["num_men"] = 160 },
	["nor_archers"] = { ["unit_key"] = "nor_archers", ["caste"] = "light", ["num_men"] = 80 },
	["nor_axe_levy"] = { ["unit_key"] = "nor_axe_levy", ["caste"] = "light", ["num_men"] = 160 },
	["nor_axemen"] = { ["unit_key"] = "nor_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["nor_catapult"] = { ["unit_key"] = "nor_catapult", ["caste"] = "light", ["num_men"] = 40 },
	["nor_cavalry"] = { ["unit_key"] = "nor_cavalry", ["caste"] = "medium", ["num_men"] = 60 },
	["nor_flemish_crossbowmen"] = { ["unit_key"] = "nor_flemish_crossbowmen", ["caste"] = "medium", ["num_men"] = 80 },
	["nor_foot_soldiers"] = { ["unit_key"] = "nor_foot_soldiers", ["caste"] = "medium", ["num_men"] = 160 },
	["nor_horsemen"] = { ["unit_key"] = "nor_horsemen", ["caste"] = "medium", ["num_men"] = 60 },
	["nor_huskarls"] = { ["unit_key"] = "nor_huskarls", ["caste"] = "heavy", ["num_men"] = 100 },
	["nor_knights"] = { ["unit_key"] = "nor_knights", ["caste"] = "medium", ["num_men"] = 60 },
	["nor_levy_archers"] = { ["unit_key"] = "nor_levy_archers", ["caste"] = "light", ["num_men"] = 80 },
	["nor_levy_spearmen"] = { ["unit_key"] = "nor_levy_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["nor_mailed_spearmen"] = { ["unit_key"] = "nor_mailed_spearmen", ["caste"] = "medium", ["num_men"] = 160 },
	["nor_maine_infantry"] = { ["unit_key"] = "nor_maine_infantry", ["caste"] = "medium", ["num_men"] = 160 },
	["nor_maine_warriors"] = { ["unit_key"] = "nor_maine_warriors", ["caste"] = "medium", ["num_men"] = 160 },
	["nor_miles"] = { ["unit_key"] = "nor_miles", ["caste"] = "heavy", ["num_men"] = 32 },
	["nor_scout_cavalry"] = { ["unit_key"] = "nor_scout_cavalry", ["caste"] = "light", ["num_men"] = 60 },
	["nor_shield_wall"] = { ["unit_key"] = "nor_shield_wall", ["caste"] = "medium", ["num_men"] = 160 },
	["nor_spearmen"] = { ["unit_key"] = "nor_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["nor_swordsmen"] = { ["unit_key"] = "nor_swordsmen", ["caste"] = "medium", ["num_men"] = 160 },
	["sco_alban_axe_warriors"] = { ["unit_key"] = "sco_alban_axe_warriors", ["caste"] = "medium", ["num_men"] = 160 },
	["sco_alban_axemen"] = { ["unit_key"] = "sco_alban_axemen", ["caste"] = "medium", ["num_men"] = 160 },
	["sco_alban_crossbowmen"] = { ["unit_key"] = "sco_alban_crossbowmen", ["caste"] = "medium", ["num_men"] = 48 },
	["sco_alban_horsemen"] = { ["unit_key"] = "sco_alban_horsemen", ["caste"] = "medium", ["num_men"] = 60 },
	["sco_alban_javelinmen"] = { ["unit_key"] = "sco_alban_javelinmen", ["caste"] = "light", ["num_men"] = 80 },
	["sco_alban_levy_javelinmen"] = { ["unit_key"] = "sco_alban_levy_javelinmen", ["caste"] = "light", ["num_men"] = 60 },
	["sco_alban_levy_spearmen"] = { ["unit_key"] = "sco_alban_levy_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["sco_alban_raiders"] = { ["unit_key"] = "sco_alban_raiders", ["caste"] = "light", ["num_men"] = 60 },
	["sco_alban_spearmen"] = { ["unit_key"] = "sco_alban_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["sco_alban_warriors"] = { ["unit_key"] = "sco_alban_warriors", ["caste"] = "heavy", ["num_men"] = 40 },
	["sco_black_blades"] = { ["unit_key"] = "sco_black_blades", ["caste"] = "heavy", ["num_men"] = 160 },
	["sco_catapult"] = { ["unit_key"] = "sco_catapult", ["caste"] = "light", ["num_men"] = 24 },
	["sco_cateran_axemen"] = { ["unit_key"] = "sco_cateran_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["sco_cateran_levy"] = { ["unit_key"] = "sco_cateran_levy", ["caste"] = "light", ["num_men"] = 160 },
	["sco_highland_archers"] = { ["unit_key"] = "sco_highland_archers", ["caste"] = "light", ["num_men"] = 60 },
	["sco_highland_levy_archers"] = { ["unit_key"] = "sco_highland_levy_archers", ["caste"] = "light", ["num_men"] = 80 },
	["sco_highland_sharpshooters"] = { ["unit_key"] = "sco_highland_sharpshooters", ["caste"] = "light", ["num_men"] = 80 },
	["sco_kings_blades"] = { ["unit_key"] = "sco_kings_blades", ["caste"] = "heavy", ["num_men"] = 40 },
	["sco_lowland_crossbowmen"] = { ["unit_key"] = "sco_lowland_crossbowmen", ["caste"] = "heavy", ["num_men"] = 36 },
	["sco_lowland_raiders"] = { ["unit_key"] = "sco_lowland_raiders", ["caste"] = "light", ["num_men"] = 24 },
	["sco_mormaer_horsemen"] = { ["unit_key"] = "sco_mormaer_horsemen", ["caste"] = "medium", ["num_men"] = 56 },
	["sco_royal_bodyguard"] = { ["unit_key"] = "sco_royal_bodyguard", ["caste"] = "heavy", ["num_men"] = 32 },
	["sco_royal_cavalry"] = { ["unit_key"] = "sco_royal_cavalry", ["caste"] = "heavy", ["num_men"] = 48 },
	["sco_royal_followers"] = { ["unit_key"] = "sco_royal_followers", ["caste"] = "heavy", ["num_men"] = 40 },
	["sco_royal_horsemen"] = { ["unit_key"] = "sco_royal_horsemen", ["caste"] = "heavy", ["num_men"] = 60 },
	["sco_schiltron"] = { ["unit_key"] = "sco_schiltron", ["caste"] = "light", ["num_men"] = 160 },
	["sco_sword_band"] = { ["unit_key"] = "sco_sword_band", ["caste"] = "medium", ["num_men"] = 80 },
	["sco_sword_warriors"] = { ["unit_key"] = "sco_sword_warriors", ["caste"] = "heavy", ["num_men"] = 80 },
	["sco_wolf_hounds"] = { ["unit_key"] = "sco_wolf_hounds", ["caste"] = "light", ["num_men"] = 24 },
	["vik_archers"] = { ["unit_key"] = "vik_archers", ["caste"] = "light", ["num_men"] = 80 },
	["vik_armoured_archers"] = { ["unit_key"] = "vik_armoured_archers", ["caste"] = "medium", ["num_men"] = 80 },
	["vik_axe_freemen"] = { ["unit_key"] = "vik_axe_freemen", ["caste"] = "light", ["num_men"] = 160 },
	["vik_axe_hersir"] = { ["unit_key"] = "vik_axe_hersir", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_axe_hirdmen"] = { ["unit_key"] = "vik_axe_hirdmen", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_berserkers"] = { ["unit_key"] = "vik_berserkers", ["caste"] = "heavy", ["num_men"] = 80 },
	["vik_catapult"] = { ["unit_key"] = "vik_catapult", ["caste"] = "light", ["num_men"] = 40 },
	["vik_freemen"] = { ["unit_key"] = "vik_freemen", ["caste"] = "light", ["num_men"] = 160 },
	["vik_great_axes"] = { ["unit_key"] = "vik_great_axes", ["caste"] = "light", ["num_men"] = 160 },
	["vik_hearthguard"] = { ["unit_key"] = "vik_hearthguard", ["caste"] = "heavy", ["num_men"] = 40 },
	["vik_hunters"] = { ["unit_key"] = "vik_hunters", ["caste"] = "light", ["num_men"] = 80 },
	["vik_huskarls"] = { ["unit_key"] = "vik_huskarls", ["caste"] = "heavy", ["num_men"] = 160 },
	["vik_jarls_huskarls"] = { ["unit_key"] = "vik_jarls_huskarls", ["caste"] = "heavy", ["num_men"] = 160 },
	["vik_javelinmen"] = { ["unit_key"] = "vik_javelinmen", ["caste"] = "light", ["num_men"] = 80 },
	["vik_jomsvikings"] = { ["unit_key"] = "vik_jomsvikings", ["caste"] = "super_heavy", ["num_men"] = 80 },
	["vik_long_axes"] = { ["unit_key"] = "vik_long_axes", ["caste"] = "light", ["num_men"] = 160 },
	["vik_mailed_archers"] = { ["unit_key"] = "vik_mailed_archers", ["caste"] = "heavy", ["num_men"] = 60 },
	["vik_mailed_hersir_axemen"] = { ["unit_key"] = "vik_mailed_hersir_axemen", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_mailed_hersir_spearmen"] = { ["unit_key"] = "vik_mailed_hersir_spearmen", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_mailed_hersir_swordsmen"] = { ["unit_key"] = "vik_mailed_hersir_swordsmen", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_mailed_huskarls"] = { ["unit_key"] = "vik_mailed_huskarls", ["caste"] = "heavy", ["num_men"] = 160 },
	["vik_marauders"] = { ["unit_key"] = "vik_marauders", ["caste"] = "light", ["num_men"] = 160 },
	["vik_raiders"] = { ["unit_key"] = "vik_raiders", ["caste"] = "light", ["num_men"] = 160 },
	["vik_royal_huskarls"] = { ["unit_key"] = "vik_royal_huskarls", ["caste"] = "heavy", ["num_men"] = 40 },
	["vik_scouts"] = { ["unit_key"] = "vik_scouts", ["caste"] = "light", ["num_men"] = 60 },
	["vik_shield_biters"] = { ["unit_key"] = "vik_shield_biters", ["caste"] = "heavy", ["num_men"] = 80 },
	["vik_skirmishers"] = { ["unit_key"] = "vik_skirmishers", ["caste"] = "light", ["num_men"] = 80 },
	["vik_spear_hersir"] = { ["unit_key"] = "vik_spear_hersir", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_spear_hirdmen"] = { ["unit_key"] = "vik_spear_hirdmen", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_sword_hersir"] = { ["unit_key"] = "vik_sword_hersir", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_sword_hirdmen"] = { ["unit_key"] = "vik_sword_hirdmen", ["caste"] = "medium", ["num_men"] = 160 },
	["vik_thrall_axemen"] = { ["unit_key"] = "vik_thrall_axemen", ["caste"] = "medium", ["num_men"] = 60 },
	["vik_thrall_spearmen"] = { ["unit_key"] = "vik_thrall_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["wel_archers"] = { ["unit_key"] = "wel_archers", ["caste"] = "light", ["num_men"] = 60 },
	["wel_armoured_axemen"] = { ["unit_key"] = "wel_armoured_axemen", ["caste"] = "very_light", ["num_men"] = 40 },
	["wel_armoured_swordsmen"] = { ["unit_key"] = "wel_armoured_swordsmen", ["caste"] = "heavy", ["num_men"] = 80 },
	["wel_axemen"] = { ["unit_key"] = "wel_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["wel_cantref_spearmen"] = { ["unit_key"] = "wel_cantref_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["wel_catapult"] = { ["unit_key"] = "wel_catapult", ["caste"] = "light", ["num_men"] = 40 },
	["wel_helwyr"] = { ["unit_key"] = "wel_helwyr", ["caste"] = "light", ["num_men"] = 32 },
	["wel_horse_raiders"] = { ["unit_key"] = "wel_horse_raiders", ["caste"] = "light", ["num_men"] = 60 },
	["wel_horsemen"] = { ["unit_key"] = "wel_horsemen", ["caste"] = "medium", ["num_men"] = 64 },
	["wel_hunters"] = { ["unit_key"] = "wel_hunters", ["caste"] = "very_heavy", ["num_men"] = 48 },
	["wel_javelinmen"] = { ["unit_key"] = "wel_javelinmen", ["caste"] = "light", ["num_men"] = 80 },
	["wel_levy_axemen"] = { ["unit_key"] = "wel_levy_axemen", ["caste"] = "light", ["num_men"] = 160 },
	["wel_levy_javelinmen"] = { ["unit_key"] = "wel_levy_javelinmen", ["caste"] = "light", ["num_men"] = 60 },
	["wel_levy_spearmen"] = { ["unit_key"] = "wel_levy_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["wel_longbowmen"] = { ["unit_key"] = "wel_longbowmen", ["caste"] = "light", ["num_men"] = 48 },
	["wel_mailed_axemen"] = { ["unit_key"] = "wel_mailed_axemen", ["caste"] = "medium", ["num_men"] = 120 },
	["wel_mailed_swordsmen"] = { ["unit_key"] = "wel_mailed_swordsmen", ["caste"] = "very_heavy", ["num_men"] = 80 },
	["wel_old_north_horsemen"] = { ["unit_key"] = "wel_old_north_horsemen", ["caste"] = "medium", ["num_men"] = 60 },
	["wel_old_north_riders"] = { ["unit_key"] = "wel_old_north_riders", ["caste"] = "medium", ["num_men"] = 60 },
	["wel_old_north_uchelwr"] = { ["unit_key"] = "wel_old_north_uchelwr", ["caste"] = "very_heavy", ["num_men"] = 48 },
	["wel_royal_spearmen"] = { ["unit_key"] = "wel_royal_spearmen", ["caste"] = "heavy", ["num_men"] = 120 },
	["wel_royal_teulu"] = { ["unit_key"] = "wel_royal_teulu", ["caste"] = "very_heavy", ["num_men"] = 32 },
	["wel_royal_uchelwr"] = { ["unit_key"] = "wel_royal_uchelwr", ["caste"] = "very_heavy", ["num_men"] = 36 },
	["wel_scout_horsemen"] = { ["unit_key"] = "wel_scout_horsemen", ["caste"] = "light", ["num_men"] = 24 },
	["wel_spearmen"] = { ["unit_key"] = "wel_spearmen", ["caste"] = "light", ["num_men"] = 160 },
	["wel_swordsmen"] = { ["unit_key"] = "wel_swordsmen", ["caste"] = "medium", ["num_men"] = 120 },
	["wel_teulu"] = { ["unit_key"] = "wel_teulu", ["caste"] = "very_heavy", ["num_men"] = 32 },
	["wel_teulu_spear_guard"] = { ["unit_key"] = "wel_teulu_spear_guard", ["caste"] = "very_heavy", ["num_men"] = 80 },
	["wel_uchelwr"] = { ["unit_key"] = "wel_uchelwr", ["caste"] = "heavy", ["num_men"] = 48 },
	["wel_valley_armoured_spearmen"] = { ["unit_key"] = "wel_valley_armoured_spearmen", ["caste"] = "medium", ["num_men"] = 160 },
	["wel_valley_mailed_spearmen"] = { ["unit_key"] = "wel_valley_mailed_spearmen", ["caste"] = "medium", ["num_men"] = 160 },
	["wel_valley_spearmen"] = { ["unit_key"] = "wel_valley_spearmen", ["caste"] = "very_light", ["num_men"] = 160 },
	["wel_war_hounds"] = { ["unit_key"] = "wel_war_hounds", ["caste"] = "light", ["num_men"] = 24 },
	["eng_north_horsemen"] = { ["unit_key"] = "eng_north_horsemen", ["caste"] = "heavy", ["num_men"] = 56},
	["eng_north_hunters"] = { ["unit_key"] = "eng_north_hunters", ["caste"] = "light", ["num_men"] = 32},
	["eng_north_spearmen"] = { ["unit_key"] = "eng_north_spearmen", ["caste"] = "light", ["num_men"] = 160},
	["eng_north_javelinmen"] = { ["unit_key"] = "eng_north_javelinmen", ["caste"] ="light", ["num_men"] = 60},
	["eng_north_champion"] = { ["unit_key"] = "eng_north_champion", ["caste"] =  "heavy", ["num_men"] = 40}
} --:map<string, {unit_key: string, caste: string, num_men: number}>

local mercenary_units = {
	--testing value.
	--["eng_ceorl_javelinmen"] = true, 
	--Sea Kings: sailors, longaxes rekkar, vikingar, Bogadrengir and berserkir are foreigners
	["est_norse_warriors"] = true,
	["est_marauders"] = true,
	["est_norse_hersir"] = true,
	["est_shield_biters"] = true,
	["est_spear_hirdmen"] = true,
	["est_long_axes"] = true,
	["est_axe_warriors"] = true,
	["vik_mailed_archers"] = true,
	--Great Viking Army: sailors, huscarls, rekkar, Sverdani, berserkir, and Vikingar are foreigners.
	["dan_ceorl_axemen"] = true,
	["dan_anglian_raiders"] = true,
	["dan_huscarls"] = true,
	["dan_berserkers"] = true,
	["dan_mailed_swordsmen"] = true,
	--Anglo Saxons: Butsecarl and huscarl are foreigners
	["eng_long_axemen"] = true, 
	["eng_royal_huscarles"] = true,
	--Gealic: Foreign Warriors
	["iri_foreign_warriors"] = true, 
	--Foreign mercenaries
	["dan_mailed_horsemen"] = true,
	["dan_anglian_marauders"] = true,
	["dan_northumbrian_mailed_thegns"] = true,
	["eng_mailed_thegns"] = true,
	["vik_jomsvikings"] = true,
	["dan_jarls_huscarls"] = true,
	-- vikingar and sailors
	["wel_mailed_axemen"] = true,
	["vik_thrall_axemen"] = true
}--:map<string, boolean>

local slave_units = {
	["est_warband"]  = true,
	["est_raiders"] = true,
	["est_kerns"] = true
} --:map<string, boolean>

local general_units = {
		--Sea Kings: 
		["est_hearthguard"] = true,
		["est_royal_huskarls"] = true,
		--Great Viking Army: 
		["dan_warlords_companions"] = true,
		["dan_royal_huscarls"] = true,
		--Anglo Saxons: 
		["eng_royal_companions"] = true, 
		["eng_royal_bodyguard"] = true,
		--Gealic:
		["iri_household_horsemen"] = true, 
		["iri_household_riders"] = true,
		--Welsh
		["wel_teulu"] = true,
		["wel_royal_teulu"] = true,
		--Scottish
		["sco_royal_followers"] = true,
		["sco_royal_bodyguard"] = true,
}--:map<string, boolean>


return {
	main_unit_size_caste_info = main_unit_size_caste_info,
	mercenary_units = mercenary_units,
	slave_units  = slave_units,
	general_units = general_units
}