return {
	[1] = {
		["PROGRESS_PAYLOAD_KEY"] = "EMPTY_PROGRESS_PAYLOAD"
	},
	[2] = {
		["PROGRESS_PAYLOAD_KEY"] = "START_BATTLE_COMPLETE"
	},
	[3] = {
		["PROGRESS_PAYLOAD_KEY"] = "INTRO_COMPLETED_EAST"
	},
	[4] = {
		["PROGRESS_PAYLOAD_KEY"] = "INTRO_COMPLETED_WEST"
	},
	[5] = {
		["PROGRESS_PAYLOAD_KEY"] = "INTRODUCTION_ACT_COMPLETED"
	}
}