return {
	[1] = {
		["PROGRESS_PAYLOAD"] = "START_BATTLE_COMPLETE",
		["PROGRESS_GATE"] = "INTRO_WEST",
		["SELECTION_SET"] = "1",
		["INCREMENT"] = "1"
	},
	[2] = {
		["PROGRESS_PAYLOAD"] = "START_BATTLE_COMPLETE",
		["PROGRESS_GATE"] = "INTRO_SOUTH",
		["SELECTION_SET"] = "2",
		["INCREMENT"] = "1"
	},
	[3] = {
		["PROGRESS_PAYLOAD"] = "START_BATTLE_COMPLETE",
		["PROGRESS_GATE"] = "INTRO_NORTH",
		["SELECTION_SET"] = "2",
		["INCREMENT"] = "1"
	},
	[4] = {
		["PROGRESS_PAYLOAD"] = "START_BATTLE_COMPLETE",
		["PROGRESS_GATE"] = "INTRO_EAST",
		["SELECTION_SET"] = "1",
		["INCREMENT"] = "1"
	},
	[5] = {
		["PROGRESS_PAYLOAD"] = "START_BATTLE_COMPLETE",
		["PROGRESS_GATE"] = "INTRODUCTION",
		["SELECTION_SET"] = "MANDATORY",
		["INCREMENT"] = "1"
	},
	[6] = {
		["PROGRESS_PAYLOAD"] = "INTRO_COMPLETED_EAST",
		["PROGRESS_GATE"] = "INTRO_EAST_S1",
		["SELECTION_SET"] = "MANDATORY",
		["INCREMENT"] = "1"
	},
	[7] = {
		["PROGRESS_PAYLOAD"] = "INTRO_COMPLETED_WEST",
		["PROGRESS_GATE"] = "INTRO_WEST_S1",
		["SELECTION_SET"] = "MANDATORY",
		["INCREMENT"] = "1"
	}
}